CREATE TABLE USERS (
  id INT AUTO_INCREMENT PRIMARY KEY,
  name VARCHAR(255) NOT NULL,
  email VARCHAR(255) NOT NULL UNIQUE,
  password  VARCHAR(255),
  phone VARCHAR(50),
  solar TINYINT(1) DEFAULT 0,
  wind TINYINT(1) DEFAULT 0,
  battery TINYINT(1) DEFAULT 0,
  other TINYINT(1) DEFAULT 0,
  message TEXT
);
